apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hub-resolver
spec:
  workspaces:
    - name: output
      emptyDir: {}
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: url
      value: https://github.com/tektoncd/pipeline.git
    - name: revision
      value: main
  taskRef:
    resolver: hub
    params:
      - name: catalog # optional
        value: Tekton
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: version
        value: "0.6"
