apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-to-list-files
spec:
  inputs:
    resources:
      - name: pipeline-git
        type: git
  outputs:
    resources:
      - name: pipeline-git
        type: git
  steps:
    - name: list
      image: ubuntu
      command:
        - bash
      args:
        - -c
        - |
          ls -al $(inputs.resources.pipeline-git.path)
---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-to-list-files
spec:
  resources:
    - name: pipeline-git
      type: git
  params:
    - name: "path"
      default: "README.md"
  tasks:
    - name: list-files
      taskRef:
        name: task-to-list-files
      resources:
        inputs:
          - name: pipeline-git
            resource: pipeline-git
        outputs:
          - name: pipeline-git
            resource: pipeline-git
    - name: second-list-files
      taskRef:
        name: task-to-list-files
      resources:
        inputs:
          - name: pipeline-git
            resource: pipeline-git
        outputs:
          - name: pipeline-git
            resource: pipeline-git
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipelinerun-with-resourcespec
spec:
  pipelineRef:
    name: pipeline-to-list-files
  serviceAccountName: 'default'
  resources:
    - name: pipeline-git
      resourceSpec:
        type: git
        params:
          - name: revision
            value: main
          - name: url
            value: https://github.com/tektoncd/pipeline
